mode = "local"
project = ""
shell = ""

[dirs]
cache = "/home/dan/.cache/hatch"
data = "/home/dan/.local/share/hatch"
project = []
python = "isolated"

[dirs.env]
virtual = ".hatch"

[projects]

[publish.index]
repo = "main"

[template]
email = "daniele.arosio@cnr.it"
name = "daniele arosio"

[template.licenses]
default = [
  "BSD-3-Clause",
]
headers = true

[template.plugins.default]
ci = true
src-layout = true
tests = true

[terminal.styles]
debug = "bold"
error = "bold red"
info = "bold"
spinner = "simpleDotsScrolling"
success = "bold cyan"
waiting = "bold magenta"
warning = "bold yellow"
