[font]
size = 12

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "Hack"
style = "Regular"

[keyboard]

[[keyboard.bindings]]
action = "Paste"
key = "Y"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "W"
mods = "Alt"
