exclude: ^src/clophfit/old/.
ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autofix_commit_msg: "style: pre-commit fixes"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files # hyper
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml # hyper
      - id: check-toml # hyper
      # - id: debug-statements
      # - id: end-of-file-fixer # hyper
      - id: mixed-line-ending
      # - id: trailing-whitespace # hyper

  # - repo: https://github.com/charliermarsh/ruff-pre-commit
  #   rev: "v0.0.241"
  #   hooks:
  #     - id: ruff

  # - repo: https://github.com/psf/black
  #   rev: 23.1.0
  #   hooks:
  #     - id: black-jupyter
  #     - id: black
  #       require_serial: true

  # - repo: https://github.com/asottile/blacken-docs
  #   rev: 1.13.0
  #   hooks:
  #     - id: blacken-docs
  #       additional_dependencies: [black]
  #       exclude: docs/tutorials/usage.*.rst

  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: "v3.0.0-alpha.4"
  #   hooks:
  #     - id: prettier
  #       types_or: [yaml, markdown, html, css, scss, javascript, json]
  #       args: [--prose-wrap=always]

  # - repo: https://github.com/asottile/pyupgrade
  #   rev: v3.3.1
  #   hooks:
  #     - id: pyupgrade
  #       args: ["--py38-plus"]

  # - repo: https://github.com/pycqa/flake8
  #   rev: 6.0.0
  #   hooks:
  #     - id: flake8
  #       additional_dependencies: [flake8-bandit, flake8-rst-docstrings]
  #       require_serial: true

  # - repo: https://github.com/codespell-project/codespell
  #   rev: v2.2.2
  #   hooks:
  #     - id: codespell

  # - repo: https://github.com/shellcheck-py/shellcheck-py
  #   rev: v0.9.0.2
  #   hooks:
  #     - id: shellcheck

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.40.0
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [push]
