repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: check-merge-conflict
  - id: check-symlinks
  - id: destroyed-symlinks
  - id: check-yaml
  - id: check-toml
      # - id: debug-statements
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: detect-private-key
  - id: trailing-whitespace

- repo: https://github.com/Yelp/detect-secrets
  rev: v1.4.0
  hooks:
  - id: detect-secrets
    args: [--baseline, .secrets.baseline, --exclude-files, emacs/.emacs.d/straight/versions/default.el, --exclude-files, goldendict/.goldendict/config]
    exclude: .hatch

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.6.0
  hooks:
  - id: pretty-format-ini
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
  - id: pretty-format-toml
    args: [--autofix]
  # - repo: https://github.com/charliermarsh/ruff-pre-commit
  #   rev: "v0.0.241"
  #   hooks:
  #     - id: ruff

  # - repo: https://github.com/psf/black
  #   rev: 23.1.0
  #   hooks:
  #     - id: black-jupyter
  #     - id: black
  #       require_serial: true

  # - repo: https://github.com/asottile/blacken-docs
  #   rev: 1.13.0
  #   hooks:
  #     - id: blacken-docs
  #       additional_dependencies: [black]
  #       exclude: docs/tutorials/usage.*.rst

  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: "v3.0.0-alpha.4"
  #   hooks:
  #     - id: prettier
  #       types_or: [yaml, markdown, html, css, scss, javascript, json]
  #       args: [--prose-wrap=always]

  # - repo: https://github.com/asottile/pyupgrade
  #   rev: v3.3.1
  #   hooks:
  #     - id: pyupgrade
  #       args: ["--py38-plus"]

  # - repo: https://github.com/pycqa/flake8
  #   rev: 6.0.0
  #   hooks:
  #     - id: flake8
  #       additional_dependencies: [flake8-bandit, flake8-rst-docstrings]
  #       require_serial: true

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.2
  hooks:
  - id: codespell
    exclude: vim/.vim/plugin|ranger/.config/ranger|vim/.vim/vimrc|goldendict/.goldendict/config

- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.9.0.2
  hooks:
  - id: shellcheck
    # args: [--severity=style]    # Show errors, warnings, info and style

- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.41.0
  hooks:
  - id: commitizen
  - id: commitizen-branch
    stages: [push]
