use_default_settings: true
server:
  secret_key: "CHANGE_THIS_TO_A_LONG_RANDOM_STRING"
  bind_address: "0.0.0.0"
  port: 8080
  public_instance: false
  limiter: false
  allowed_media_types:
    - text/html
    - application/json
engines:
  - name: google_scholar
    disabled: false
  - name: pubmed
    disabled: false
  - name: semantic_scholar
    disabled: false
  - name: arxiv
    disabled: false
  - name: crossref
    disabled: false
  - name: wolframalpha
    disabled: false
  - name: ahmia
    disabled: true
  - name: torch
    disabled: true
  - name: wikidata
    disabled: true
categories_as_tabs:
  scientific:
    - pubmed
    - google_scholar
    - semantic_scholar
    - arxiv
search:
  safe_search: 0
  autocomplete: ""
  formats:
    - html
    - json
