use_default_settings: true
server:
  secret_key: "CHANGE_THIS_TO_A_LONG_RANDOM_STRING"
  bind_address: "0.0.0.0"
  port: 8080
  public_instance: false
  limiter: false
  allowed_media_types:
    - text/html
    - application/json
search:
  formats:
    - html
    - json
  safe_search: 0
